const lang = {
  en: {
    s03: {
      desc: "Each KLAY UNIVERSE NFT is an explorable,\nlimitless world that can be built into anything you can imagine.",
    },
    s04: {
      q2_01: "Minecraft supported",
      q2_02: "All 5,000 UNIVERSE minted",
      q2_03: "UNIVERSE rarity & distribution data separation completed",
      q2_04: "UNIVERSE syncing to update UNIVERSE on the blockchain",
      q2_05: "Open sourcemultiplayer server released",
      q2_06: "Cross-platform playable (Xbox, PS, Switch, Phones, Tablets)",
      q2_07: "COMMUNITY build-up",
      q2_08: "Compensation plans for UNIVERSE holders",
      q3_01: "Payments dApp for in-game $KUT transaction",
      q3_02: "Support for UNIVERSE owner created P2E systems",
      q3_03: "Support for playable 3D NFT character partnerships",
      q3_04: "Support for playing GAME on KLAY UNIVERSE",
      q3_05: "Collaboration with Famous companies and Celebrities",
      q3_06: "Famous brand UNIVERSE is open",
      q3_07: "Full support&compensation to builders and creators",
      q3_08: "Full support for creations such as animations and webtoons",
      q3_09: "$KUT token Release",
      q3_10: "$KUT token will list CEX & DEX",
      q3_11: "Based on $KUT voting system and compensation plans for $KUT token holders",
      q3_12: "AIRDROPS $KUT for UNIVERSE holders",
      q3_13: "Partnership and Collaboration with other KLAYTN projects",
    },
    s05: {
      desc: "The Klay Universe team is more passionate than anyone else,\n It consists of talented team members full of affection.",
    },
    s06: {
      desc: "Klay Universe is with creative and outstanding partners to expand its broader worldview.",
    },
  },
  kr: {
    s03: {
      desc: "각 각의  KLAY UNIVERSE NFT는 탐색이 가능하며, \n 당신이 상상할 수 있는 모든 것을 만들 수 있는 제한이 없는 세계입니다.",
    },
    s04: {
      q2_01: "Minecraft에 KlayUniverse 연동",
      q2_02: "5,000 Universe NFT 민팅",
      q2_03: "Universe 레어리티 및 특성 작업",
      q2_04: "Universe 동기화 및 블록체인 상에 정보 업데이트",
      q2_05: "오픈소스 멀티플레이어 서버 출시",
      q2_06: "Xbox, PS, Switch, Phones, Tablets)  (PC, 콘솔 및 모바일 기기 지원 예정",
      q2_07: "커뮤니티 활성화",
      q2_08: "Universe 홀더 보상 계획 발표",
      q3_01: "$KUT 보상 지급을 위한 인게임 dApp 개발",
      q3_02: "Universe 소유자를 위한 P2E 시스템 지원",
      q3_03: "3D 캐릭터 파트너를 위한 시스템 지원",
      q3_04: "KlayUniverse의 게임 콘텐츠 지원",
      q3_05: "유명 기업 및 셀럽과의 협업",
      q3_06: "UNIVERSE에 브랜드관 오픈",
      q3_07: "빌더와 크레이이터들을 위한 전폭적인 지원과 보상",
      q3_08: "애니메이션 및 웹툰 등의 2차 창작물 및 창작자 지원",
      q3_09: "$KUT 토큰 출시",
      q3_10: "$KUT 토큰 CEX 및 DEX 상장 예정",
      q3_11: "$KUT 토큰 홀더 보상 지급 및 $KUT 투표 시스템 지원 예정",
      q3_12: "UNIVERSE 홀더에게 $KUT 토큰 에어드랍 진행 예정",
      q3_13: "KLAYTN 생태계 프로젝트들과 협업 및 파트너십",
    },
    s05: {
      desc: "The Klay Universe 팀은 누구보다도 열정적이고\n프로젝트에 애정이 넘치는 실력파 팀원들로 구성되어 있습니다.",
    },
    s06: {
      desc: "Klay Universe는 더 넓은 세계관 확장을 위해 창의적이고 뛰어난 파트너와 함께합니다.",
    },
  },
};
